{{- if eq .Values.regioncode "ne" }}
apiVersion: devops.uniphar.ie/v1
kind: PlatformDataPilotAdxDatabase
metadata:
# database is devops, we will use DotFlyerSMSs and DotFlyerEmails for the tables
  name: devops
  namespace: platform-app
spec:
  # 10 years retention for soft delete, 2 weeks for hot cache
  softDeleteRetentionDays: 3650 
  hotCachePeriodDays: 14
  access:
    workloadIdentity:
      name: compute-aks-platform-app-dev-k8s-sa
      namespace: platform-app
{{- end }}
