kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}-app
    service: {{ .Chart.Name }}-service
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      service: {{ .Chart.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
        service: {{ .Chart.Name }}-service
        app.kubernetes.io/name: {{ .Chart.Name }}
        azure.workload.identity/use: "true"
      annotations:
        {{- with .Values.podAnnotations }}{{- toYaml . | nindent 8 }}{{- end }}
    spec:
      serviceAccountName: {{ .Values.AKSClusterSAName }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.ACRName }}.azurecr.io/{{ .Chart.Name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            - name: "AZURE_KEY_VAULT_NAME"
              value: {{ .Values.AzureKeyVaultName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        agentpool: platform