apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-srv
  labels:
    app: {{ .Chart.Name }}-app
    service: {{ .Chart.Name }}-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Chart.Name }}
  selector:
    service: {{ .Chart.Name }}-service