name: CD for DotFlyer Common Package

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/dotflyer-common-package-cd.yaml
      - src/DotFlyer.Common/**

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  Package_CD:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Pack
        working-directory: ./src/DotFlyer.Common
        run: dotnet pack --configuration Release -o ./nupkgs