name: CD for DotFlyer Common Package

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/dotflyer-common-package-cd.yaml

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  Package_CD:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"