name: CI for DotFlyer Service

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/dotflyer-api-ci.yaml
      - .github/workflows/shared-app-ci-workflow.yaml
      - src/DotFlyer.Service/**

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  DotFlyerService_CI:
    uses: ./.github/workflows/shared-app-ci-workflow.yaml
    secrets:
      ACTIONS_AUTH_APP_ID: ${{ secrets.ACTIONS_AUTH_APP_ID }}
      ACTIONS_AUTH_APP_PRIVATE_KEY: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}
    with:
      applicationFolder: DotFlyer.Service