name: CI for Dotflyer Service

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/Dotflyer.Service/**"

permissions:
  id-token: write
  contents: read

jobs:
  DotflyerService_CI:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello"