name: CD for DotFlyer Common Package

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/dotflyer-common-package-cd.yaml
      - src/DotFlyer.Common/**

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  Package_CD:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Pack
        working-directory: ./src/DotFlyer.Common
        run: dotnet pack --configuration Release -o ./.nupkgs
      
      - name: gh-app-install token
        id: gh-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.ACTIONS_AUTH_APP_ID }}
          private_key: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}

      - name: checkout devops-azure repo
        uses: actions/checkout@v3
        with:
          path: devops-azure
          repository: Uniphar/devops-azure
          token: ${{ steps.gh-app.outputs.token }}

      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_PLATFORM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: get NuGet repository API key
        shell: pwsh
        run: |
          Import-Module .\devops-azure\src\Uniphar.DevOps.psd1 -ErrorAction Stop -Force

          $coreKeyVaultName = Resolve-UniResourceName 'keyvault' $p_corePlatformProject
          $nuGetAPIKeySecret = Get-AzKeyVaultSecret -VaultName $coreKeyVaultName -Name nuget-org-repository-api-key
          $nuGetAPIKey = ConvertFrom-SecureString $nuGetAPIKeySecret.SecretValue -AsPlainText

          echo "NUGET_API_KEY=$nuGetAPIKey" >> $env:GITHUB_ENV