name: CI for Dotflyer API

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/Dotflyer.Api/**"

permissions:
  id-token: write
  contents: read

jobs:
  DotflyerApi_CI:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello"