name: CI for DotFlyer API

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/dotflyer-api-ci.yaml
      - .github/workflows/shared-app-ci-workflow.yaml
      - src/DotFlyer.Api/**

permissions:
  id-token: write
  contents: read

jobs:
  DotFlyerApi_CI:
    uses: ./.github/workflows/shared-app-ci-workflow.yaml
    with:
      applicationFolder: DotFlyer.Api