name: CI for Dotflyer Service

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/dotflyer-api-ci.yaml
      - .github/workflows/shared-app-ci-workflow.yaml
      - src/Dotflyer.Service/**

permissions:
  id-token: write
  contents: read

jobs:
  DotflyerService_CI:
    uses: ./.github/workflows/shared-app-ci-workflow.yaml
    with:
      applicationName: Dotflyer.Service