name: CI for DotFlyer Common Package

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/dotflyer-common-package-ci.yaml
      - src/DotFlyer.Common/**

permissions:
  id-token: write
  contents: read

jobs:
  Package_CI:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'
      
      - name: check for NuGet vulnerabilites
        working-directory: ./src/DotFlyer.Common
        shell: pwsh
        run: |
            dotnet restore
            dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
            echo "Analyze dotnet list package command log output..."
            exit (Select-String -Path "build.log" -Pattern "has the following vulnerable packages" -AllMatches).Matches.Count -gt 0 ? 1 : 0
      
      - name: dotnet build
        working-directory: ./src/DotFlyer.Common
        run: |
          dotnet build