name: CD for Dotflyer Service

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "src/Dotflyer.Service/**"

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  DotflyerService_CD:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"