name: CD for importing API into APIM

on:
  workflow_call:
    secrets:
      AZURE_TENANT_ID:
        required: true
        description: 'Azure Tenant ID'
      AZURE_CLIENT_ID:
        required: true
        description: 'Azure Client ID'
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: 'Azure Subscription ID'

    inputs:
      environment:
        type: string
        required: true
        description: 'environment to deploy to'

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  import_api_CD:
    runs-on: ubuntu-latest
    steps:
      - name: gh-app-install token
        id: gh-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.ACTIONS_AUTH_APP_ID }}
          private_key: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}

      - name: checkout devops-azure repo
        uses: actions/checkout@v4
        with:
          path: devops-azure
          repository: Uniphar/devops-azure
          ref: feature/import-apim
          token: ${{ steps.gh-app.outputs.token }}

      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Import API into APIM
        uses: azure/powershell@v2
        with: 
          inlineScript: |
            Import-Module .\devops-azure\src\Uniphar.DevOps.psd1 -ErrorAction Stop -Force
            Import-UniApimApi ${{ inputs.environment }} 'Dotflyer.Api' 'dotflyer' 'dotflyer/open-api/v1' -Verbose -ErrorAction Stop
          azPSVersion: "latest"
          errorActionPreference: 'stop'
          failOnStandardError: true